/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Dhaval Popat
 */
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.io.*;
import java.util.*;
import java.lang.*;

public class main extends javax.swing.JFrame {
Connection conn=null;
ResultSet rs=null;
Statement st=null;
String u,clas;
String uname,city,state,country,username,password,securityq,ans,codeans;
int date,month,year;
String d1,m1,y1;
int d,m,y;
String from1,to1;
int uans,gans=0;
double price,totprice;
int eseats=100,bseats=50,fseats=50;
int seats,no=0;
String da;
String cclas;
String book_from,book_to,book_class;
    /**
     * Creates new form main
     */
    public main() {
        initComponents();
        Display.setEditable(false); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contactus = new javax.swing.JFrame();
        jLabel44 = new javax.swing.JLabel();
        newuserback1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        search = new javax.swing.JFrame();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel95 = new javax.swing.JLabel();
        sear = new javax.swing.JButton();
        showall = new javax.swing.JButton();
        editback1 = new javax.swing.JLabel();
        fc1 = new javax.swing.JComboBox();
        dd = new javax.swing.JComboBox();
        tc1 = new javax.swing.JComboBox();
        jLabel22 = new javax.swing.JLabel();
        md = new javax.swing.JComboBox();
        jLabel23 = new javax.swing.JLabel();
        yd = new javax.swing.JComboBox();
        jButton4 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        login = new javax.swing.JFrame();
        usern = new javax.swing.JTextField();
        jLabel58 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        pword = new javax.swing.JPasswordField();
        logn = new javax.swing.JButton();
        loginback = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        signup = new javax.swing.JFrame();
        na = new javax.swing.JTextField();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        cit = new javax.swing.JTextField();
        jLabel66 = new javax.swing.JLabel();
        stat = new javax.swing.JTextField();
        jLabel67 = new javax.swing.JLabel();
        coun = new javax.swing.JTextField();
        jLabel68 = new javax.swing.JLabel();
        dat = new javax.swing.JTextField();
        jLabel75 = new javax.swing.JLabel();
        mon = new javax.swing.JTextField();
        jLabel74 = new javax.swing.JLabel();
        yer = new javax.swing.JTextField();
        jLabel69 = new javax.swing.JLabel();
        userna = new javax.swing.JTextField();
        jLabel70 = new javax.swing.JLabel();
        pass = new javax.swing.JPasswordField();
        jLabel63 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        createacc = new javax.swing.JButton();
        code = new javax.swing.JTextField();
        newuserback = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        user = new javax.swing.JFrame();
        jLabel83 = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        logout = new javax.swing.JLabel();
        sflight = new javax.swing.JButton();
        eprofile = new javax.swing.JButton();
        branches = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        update = new javax.swing.JFrame();
        jLabel90 = new javax.swing.JLabel();
        ename = new javax.swing.JTextField();
        jLabel91 = new javax.swing.JLabel();
        ecity = new javax.swing.JTextField();
        jLabel92 = new javax.swing.JLabel();
        estat = new javax.swing.JTextField();
        jLabel93 = new javax.swing.JLabel();
        ecoun = new javax.swing.JTextField();
        jLabel94 = new javax.swing.JLabel();
        edat = new javax.swing.JTextField();
        jLabel101 = new javax.swing.JLabel();
        emon = new javax.swing.JTextField();
        jLabel100 = new javax.swing.JLabel();
        eyr = new javax.swing.JTextField();
        jLabel96 = new javax.swing.JLabel();
        epass = new javax.swing.JTextField();
        update1 = new javax.swing.JButton();
        editback = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        record = new javax.swing.JFrame();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb1 = new javax.swing.JTable();
        jLabel17 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        other = new javax.swing.JLabel();
        book = new javax.swing.JFrame();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        fc = new javax.swing.JComboBox();
        tc = new javax.swing.JComboBox();
        jLabel14 = new javax.swing.JLabel();
        cc = new javax.swing.JComboBox();
        jLabel15 = new javax.swing.JLabel();
        seat = new javax.swing.JTextField();
        proceed = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        dc1 = new javax.swing.JComboBox();
        jLabel19 = new javax.swing.JLabel();
        dc2 = new javax.swing.JComboBox();
        jLabel20 = new javax.swing.JLabel();
        dc3 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        Bill = new javax.swing.JFrame();
        jLabel217 = new javax.swing.JLabel();
        ok = new javax.swing.JButton();
        jScrollPane8 = new javax.swing.JScrollPane();
        Display = new javax.swing.JTextArea();
        end = new javax.swing.JFrame();
        jLabel221 = new javax.swing.JLabel();
        lout = new javax.swing.JButton();
        gouseracc = new javax.swing.JButton();
        jLabel223 = new javax.swing.JLabel();
        jLabel222 = new javax.swing.JLabel();
        payment = new javax.swing.JDialog();
        totamt = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        dcard = new javax.swing.JRadioButton();
        ccard = new javax.swing.JRadioButton();
        jLabel219 = new javax.swing.JLabel();
        bank = new javax.swing.JTextField();
        jLabel220 = new javax.swing.JLabel();
        cno = new javax.swing.JTextField();
        cont = new javax.swing.JButton();
        bg1 = new javax.swing.ButtonGroup();
        contus = new javax.swing.JLabel();
        searchfield = new javax.swing.JLabel();
        sup = new javax.swing.JLabel();
        sin = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        contactus.setMinimumSize(new java.awt.Dimension(686, 377));
        contactus.getContentPane().setLayout(null);

        jLabel44.setBackground(new java.awt.Color(255, 255, 255));
        jLabel44.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel44.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel44.setText("<html> <body> INDIAN AIRLINES <br> FLORENCE BUILDING, 25th FLOOR, <br> SECTOR-20,CUFFE PARADE, <br> MUMBAI. <br> Ph no: 022-27715639 </body> </html>");
        jLabel44.setOpaque(true);
        contactus.getContentPane().add(jLabel44);
        jLabel44.setBounds(20, 200, 340, 120);

        newuserback1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        newuserback1.setForeground(new java.awt.Color(255, 255, 255));
        newuserback1.setText("<<BACK");
        newuserback1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        newuserback1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newuserback1MouseClicked(evt);
            }
        });
        contactus.getContentPane().add(newuserback1);
        newuserback1.setBounds(570, 10, 80, 17);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/3.png"))); // NOI18N
        contactus.getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 670, 350);

        search.setMinimumSize(new java.awt.Dimension(517, 324));
        search.getContentPane().setLayout(null);

        jLabel8.setText("TO:");
        search.getContentPane().add(jLabel8);
        jLabel8.setBounds(248, 50, 30, 14);

        jLabel9.setText("FROM:");
        search.getContentPane().add(jLabel9);
        jLabel9.setBounds(36, 47, 50, 14);

        jLabel95.setText("DATE:");
        search.getContentPane().add(jLabel95);
        jLabel95.setBounds(50, 110, 40, 14);

        sear.setText("SEARCH");
        sear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searActionPerformed(evt);
            }
        });
        search.getContentPane().add(sear);
        sear.setBounds(60, 170, 160, 30);

        showall.setText("SHOW ALL FLIGHTS");
        showall.setMaximumSize(new java.awt.Dimension(600, 400));
        showall.setMinimumSize(new java.awt.Dimension(513, 317));
        showall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showallActionPerformed(evt);
            }
        });
        search.getContentPane().add(showall);
        showall.setBounds(250, 170, 160, 30);

        editback1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        editback1.setText("<<BACK");
        editback1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editback1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editback1MouseClicked(evt);
            }
        });
        search.getContentPane().add(editback1);
        editback1.setBounds(420, 10, 80, 17);

        fc1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "MUMBAI", "DELHI", "KOLKATA", "CHENNAI" }));
        fc1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fc1ActionPerformed(evt);
            }
        });
        search.getContentPane().add(fc1);
        fc1.setBounds(90, 40, 140, 30);

        dd.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "10", "11", "12", " " }));
        search.getContentPane().add(dd);
        dd.setBounds(90, 100, 60, 30);

        tc1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "MUMBAI", "DELHI", "KOLKATA", "CHENNAI" }));
        tc1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tc1ActionPerformed(evt);
            }
        });
        search.getContentPane().add(tc1);
        tc1.setBounds(280, 40, 140, 30);

        jLabel22.setText("/");
        search.getContentPane().add(jLabel22);
        jLabel22.setBounds(160, 110, 4, 14);

        md.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "10", "11", "12" }));
        search.getContentPane().add(md);
        md.setBounds(180, 100, 80, 30);

        jLabel23.setText("/");
        search.getContentPane().add(jLabel23);
        jLabel23.setBounds(280, 110, 4, 14);

        yd.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2014" }));
        search.getContentPane().add(yd);
        yd.setBounds(300, 100, 90, 30);

        jButton4.setText("SHOW DIFFERENT FLIGHT GROUPS");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        search.getContentPane().add(jButton4);
        jButton4.setBounds(110, 230, 280, 30);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/7.jpg"))); // NOI18N
        search.getContentPane().add(jLabel10);
        jLabel10.setBounds(0, 0, 520, 360);

        login.setMinimumSize(new java.awt.Dimension(603, 270));
        login.getContentPane().setLayout(null);
        login.getContentPane().add(usern);
        usern.setBounds(140, 50, 260, 30);

        jLabel58.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel58.setText("Username:");
        login.getContentPane().add(jLabel58);
        jLabel58.setBounds(60, 50, 150, 17);

        jLabel57.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel57.setText("Password:");
        login.getContentPane().add(jLabel57);
        jLabel57.setBounds(60, 120, 150, 17);
        login.getContentPane().add(pword);
        pword.setBounds(140, 110, 260, 30);

        logn.setText("LOGIN");
        logn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lognActionPerformed(evt);
            }
        });
        login.getContentPane().add(logn);
        logn.setBounds(220, 170, 120, 30);

        loginback.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        loginback.setText("<<BACK");
        loginback.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginback.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginbackMouseClicked(evt);
            }
        });
        login.getContentPane().add(loginback);
        loginback.setBounds(490, 10, 70, 17);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/2.png"))); // NOI18N
        login.getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 590, 270);

        signup.setMinimumSize(new java.awt.Dimension(614, 655));
        signup.getContentPane().setLayout(null);

        na.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                naActionPerformed(evt);
            }
        });
        signup.getContentPane().add(na);
        na.setBounds(140, 30, 200, 30);

        jLabel64.setText("Name:");
        signup.getContentPane().add(jLabel64);
        jLabel64.setBounds(80, 40, 60, 14);

        jLabel65.setText("City:");
        signup.getContentPane().add(jLabel65);
        jLabel65.setBounds(90, 90, 40, 14);
        signup.getContentPane().add(cit);
        cit.setBounds(140, 80, 200, 30);

        jLabel66.setText("State:");
        signup.getContentPane().add(jLabel66);
        jLabel66.setBounds(90, 140, 40, 14);
        signup.getContentPane().add(stat);
        stat.setBounds(140, 130, 200, 30);

        jLabel67.setText("Country:");
        signup.getContentPane().add(jLabel67);
        jLabel67.setBounds(80, 190, 60, 14);
        signup.getContentPane().add(coun);
        coun.setBounds(140, 180, 200, 30);

        jLabel68.setText("Date of birth:");
        signup.getContentPane().add(jLabel68);
        jLabel68.setBounds(60, 240, 80, 14);
        signup.getContentPane().add(dat);
        dat.setBounds(140, 230, 40, 30);

        jLabel75.setText("/");
        signup.getContentPane().add(jLabel75);
        jLabel75.setBounds(190, 240, 20, 14);

        mon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monActionPerformed(evt);
            }
        });
        signup.getContentPane().add(mon);
        mon.setBounds(210, 230, 40, 30);

        jLabel74.setText("/");
        signup.getContentPane().add(jLabel74);
        jLabel74.setBounds(260, 240, 20, 14);
        signup.getContentPane().add(yer);
        yer.setBounds(280, 230, 70, 30);

        jLabel69.setText("Username:");
        signup.getContentPane().add(jLabel69);
        jLabel69.setBounds(70, 290, 80, 14);
        signup.getContentPane().add(userna);
        userna.setBounds(140, 280, 200, 30);

        jLabel70.setText("Password:");
        signup.getContentPane().add(jLabel70);
        jLabel70.setBounds(70, 340, 80, 14);
        signup.getContentPane().add(pass);
        pass.setBounds(140, 330, 200, 30);

        jLabel63.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel63.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/code.png"))); // NOI18N
        jLabel63.setBorder(new javax.swing.border.MatteBorder(null));
        jLabel63.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        signup.getContentPane().add(jLabel63);
        jLabel63.setBounds(140, 390, 220, 90);

        jLabel73.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel73.setText("Enter the above code:");
        signup.getContentPane().add(jLabel73);
        jLabel73.setBounds(-10, 520, 140, 14);

        createacc.setText("CREATE MY ACCOUNT");
        createacc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createaccActionPerformed(evt);
            }
        });
        signup.getContentPane().add(createacc);
        createacc.setBounds(170, 580, 170, 30);

        code.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codeActionPerformed(evt);
            }
        });
        signup.getContentPane().add(code);
        code.setBounds(140, 520, 200, 30);

        newuserback.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        newuserback.setText("<<BACK");
        newuserback.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        newuserback.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newuserbackMouseClicked(evt);
            }
        });
        signup.getContentPane().add(newuserback);
        newuserback.setBounds(440, 10, 80, 17);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/5.jpg"))); // NOI18N
        signup.getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 600, 640);

        user.setMinimumSize(new java.awt.Dimension(485, 268));
        user.getContentPane().setLayout(null);

        jLabel83.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel83.setText("WELCOME");
        user.getContentPane().add(jLabel83);
        jLabel83.setBounds(10, 20, 80, 17);

        name.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        user.getContentPane().add(name);
        name.setBounds(90, 20, 200, 20);

        logout.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        logout.setText("LOGOUT");
        logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });
        user.getContentPane().add(logout);
        logout.setBounds(400, 10, 60, 15);

        sflight.setBackground(new java.awt.Color(102, 255, 0));
        sflight.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        sflight.setText("SEARCH FLIGHT");
        sflight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sflightActionPerformed(evt);
            }
        });
        user.getContentPane().add(sflight);
        sflight.setBounds(120, 70, 250, 25);

        eprofile.setBackground(new java.awt.Color(255, 51, 51));
        eprofile.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        eprofile.setText("EDIT MY PROFILE");
        eprofile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eprofileActionPerformed(evt);
            }
        });
        user.getContentPane().add(eprofile);
        eprofile.setBounds(120, 120, 250, 25);

        branches.setBackground(new java.awt.Color(102, 255, 0));
        branches.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        branches.setText("BOOK FLIGHT");
        branches.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                branchesActionPerformed(evt);
            }
        });
        user.getContentPane().add(branches);
        branches.setBounds(120, 170, 250, 25);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/6.png"))); // NOI18N
        user.getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 570, 250);

        update.setMinimumSize(new java.awt.Dimension(562, 410));
        update.getContentPane().setLayout(null);

        jLabel90.setForeground(new java.awt.Color(255, 255, 255));
        jLabel90.setText("Name:");
        update.getContentPane().add(jLabel90);
        jLabel90.setBounds(90, 40, 50, 14);

        ename.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enameActionPerformed(evt);
            }
        });
        update.getContentPane().add(ename);
        ename.setBounds(140, 30, 200, 30);

        jLabel91.setForeground(new java.awt.Color(255, 255, 255));
        jLabel91.setText("City:");
        update.getContentPane().add(jLabel91);
        jLabel91.setBounds(100, 90, 40, 14);

        ecity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ecityActionPerformed(evt);
            }
        });
        update.getContentPane().add(ecity);
        ecity.setBounds(140, 80, 200, 30);

        jLabel92.setForeground(new java.awt.Color(255, 255, 255));
        jLabel92.setText("State:");
        update.getContentPane().add(jLabel92);
        jLabel92.setBounds(90, 140, 40, 14);

        estat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estatActionPerformed(evt);
            }
        });
        update.getContentPane().add(estat);
        estat.setBounds(140, 130, 200, 30);

        jLabel93.setForeground(new java.awt.Color(255, 255, 255));
        jLabel93.setText("Country:");
        update.getContentPane().add(jLabel93);
        jLabel93.setBounds(80, 190, 60, 14);
        update.getContentPane().add(ecoun);
        ecoun.setBounds(140, 180, 200, 30);

        jLabel94.setForeground(new java.awt.Color(255, 255, 255));
        jLabel94.setText("Date of birth:");
        update.getContentPane().add(jLabel94);
        jLabel94.setBounds(60, 240, 80, 14);

        edat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edatActionPerformed(evt);
            }
        });
        update.getContentPane().add(edat);
        edat.setBounds(140, 230, 40, 30);

        jLabel101.setForeground(new java.awt.Color(255, 255, 255));
        jLabel101.setText("/");
        update.getContentPane().add(jLabel101);
        jLabel101.setBounds(190, 240, 20, 14);

        emon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emonActionPerformed(evt);
            }
        });
        update.getContentPane().add(emon);
        emon.setBounds(200, 230, 40, 30);

        jLabel100.setForeground(new java.awt.Color(255, 255, 255));
        jLabel100.setText("/");
        update.getContentPane().add(jLabel100);
        jLabel100.setBounds(250, 240, 20, 14);

        eyr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eyrActionPerformed(evt);
            }
        });
        update.getContentPane().add(eyr);
        eyr.setBounds(260, 230, 90, 30);

        jLabel96.setForeground(new java.awt.Color(255, 255, 255));
        jLabel96.setText("Password:");
        update.getContentPane().add(jLabel96);
        jLabel96.setBounds(70, 290, 80, 14);
        update.getContentPane().add(epass);
        epass.setBounds(140, 280, 200, 30);

        update1.setText("UPDATE");
        update1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update1ActionPerformed(evt);
            }
        });
        update.getContentPane().add(update1);
        update1.setBounds(150, 340, 160, 30);

        editback.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        editback.setForeground(new java.awt.Color(255, 255, 255));
        editback.setText("<<BACK");
        editback.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editback.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editbackMouseClicked(evt);
            }
        });
        update.getContentPane().add(editback);
        editback.setBounds(470, 10, 80, 17);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/4.jpg"))); // NOI18N
        update.getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 600, 390);

        record.setMinimumSize(new java.awt.Dimension(1100, 388));
        record.getContentPane().setLayout(null);

        jLabel16.setText("FLIGHTS");
        record.getContentPane().add(jLabel16);
        jLabel16.setBounds(10, 11, 90, 20);

        tb1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "FROM", "TO", "DATE", "DEPARTURE TIME", "ARRIVAL TIME", "ECONOMY", "BUSINESS", "FIRST CLASS"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tb1);

        record.getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 50, 950, 130);

        jLabel17.setText("SELECT FLIGHT NO");
        record.getContentPane().add(jLabel17);
        jLabel17.setBounds(20, 220, 140, 14);
        record.getContentPane().add(jTextField3);
        jTextField3.setBounds(180, 210, 100, 30);

        jButton2.setText("BOOK FLIGHT>>");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        record.getContentPane().add(jButton2);
        jButton2.setBounds(800, 210, 170, 30);

        jLabel18.setText("<<BACK");
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel18MouseClicked(evt);
            }
        });
        record.getContentPane().add(jLabel18);
        jLabel18.setBounds(910, 20, 70, 20);

        jLabel24.setText("Other recommended flights:");
        record.getContentPane().add(jLabel24);
        jLabel24.setBounds(30, 280, 180, 20);
        record.getContentPane().add(other);
        other.setBounds(210, 280, 410, 30);

        book.setMinimumSize(new java.awt.Dimension(430, 460));
        book.getContentPane().setLayout(null);

        jLabel11.setText("FROM:");
        book.getContentPane().add(jLabel11);
        jLabel11.setBounds(30, 40, 50, 14);

        jLabel12.setText("TO:");
        book.getContentPane().add(jLabel12);
        jLabel12.setBounds(30, 100, 50, 14);

        fc.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "MUMBAI", "DELHI", "KOLKATA", "CHENNAI" }));
        fc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fcActionPerformed(evt);
            }
        });
        book.getContentPane().add(fc);
        fc.setBounds(90, 30, 140, 30);

        tc.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "DELHI", "MUMBAI", "KOLKATA", "CHENNAI" }));
        tc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tcActionPerformed(evt);
            }
        });
        book.getContentPane().add(tc);
        tc.setBounds(90, 90, 140, 30);

        jLabel14.setText("CLASS:");
        book.getContentPane().add(jLabel14);
        jLabel14.setBounds(30, 160, 70, 14);

        cc.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ECONOMY", "BUSINESS", "FIRST" }));
        book.getContentPane().add(cc);
        cc.setBounds(90, 150, 140, 30);

        jLabel15.setText("NO OF SEATS:");
        book.getContentPane().add(jLabel15);
        jLabel15.setBounds(10, 280, 100, 14);
        book.getContentPane().add(seat);
        seat.setBounds(100, 270, 100, 30);

        proceed.setText("PROCEED>>");
        proceed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proceedActionPerformed(evt);
            }
        });
        book.getContentPane().add(proceed);
        proceed.setBounds(20, 330, 120, 30);

        jLabel21.setText("<<BACK");
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel21MouseClicked(evt);
            }
        });
        book.getContentPane().add(jLabel21);
        jLabel21.setBounds(330, 10, 60, 20);

        jLabel13.setText("DATE:");
        book.getContentPane().add(jLabel13);
        jLabel13.setBounds(30, 220, 50, 14);

        dc1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "10", "11", "12", " " }));
        book.getContentPane().add(dc1);
        dc1.setBounds(90, 210, 70, 30);

        jLabel19.setText("/");
        book.getContentPane().add(jLabel19);
        jLabel19.setBounds(180, 220, 4, 14);

        dc2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "10", "11", "12" }));
        book.getContentPane().add(dc2);
        dc2.setBounds(200, 210, 70, 30);

        jLabel20.setText("/");
        book.getContentPane().add(jLabel20);
        jLabel20.setBounds(280, 220, 4, 14);

        dc3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2014" }));
        book.getContentPane().add(dc3);
        dc3.setBounds(300, 210, 70, 30);

        jButton1.setText("PREDICT DISCOUNTED PRICE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        book.getContentPane().add(jButton1);
        jButton1.setBounds(160, 330, 250, 30);

        jButton3.setText("CHECK TICKET AVAILABILITY");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        book.getContentPane().add(jButton3);
        jButton3.setBounds(70, 380, 260, 30);

        Bill.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        Bill.setMinimumSize(new java.awt.Dimension(400, 500));

        jLabel217.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel217.setForeground(new java.awt.Color(255, 51, 0));
        jLabel217.setText("Bill");

        ok.setText("OK");
        ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okActionPerformed(evt);
            }
        });

        Display.setColumns(20);
        Display.setRows(5);
        jScrollPane8.setViewportView(Display);

        javax.swing.GroupLayout BillLayout = new javax.swing.GroupLayout(Bill.getContentPane());
        Bill.getContentPane().setLayout(BillLayout);
        BillLayout.setHorizontalGroup(
            BillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BillLayout.createSequentialGroup()
                .addContainerGap(140, Short.MAX_VALUE)
                .addComponent(ok, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(123, 123, 123))
            .addGroup(BillLayout.createSequentialGroup()
                .addGroup(BillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BillLayout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(jLabel217, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(BillLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        BillLayout.setVerticalGroup(
            BillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BillLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel217)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ok)
                .addContainerGap())
        );

        end.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        end.setMinimumSize(new java.awt.Dimension(859, 235));
        end.getContentPane().setLayout(null);

        jLabel221.setBackground(new java.awt.Color(51, 204, 0));
        jLabel221.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel221.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel221.setText("Thank you for choosing Indian Airlines ");
        jLabel221.setOpaque(true);
        end.getContentPane().add(jLabel221);
        jLabel221.setBounds(10, 30, 820, 40);

        lout.setText("LOGOUT");
        lout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loutActionPerformed(evt);
            }
        });
        end.getContentPane().add(lout);
        lout.setBounds(360, 110, 90, 23);

        gouseracc.setText("GO TO USER ACCOUNT");
        gouseracc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gouseraccActionPerformed(evt);
            }
        });
        end.getContentPane().add(gouseracc);
        gouseracc.setBounds(320, 160, 180, 23);
        end.getContentPane().add(jLabel223);
        jLabel223.setBounds(400, 80, 140, 130);
        end.getContentPane().add(jLabel222);
        jLabel222.setBounds(0, 0, 640, 220);

        payment.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        payment.setMinimumSize(new java.awt.Dimension(595, 397));
        payment.getContentPane().setLayout(null);

        totamt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        payment.getContentPane().add(totamt);
        totamt.setBounds(20, 30, 540, 30);

        jPanel16.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Mode of payment", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.BELOW_TOP));

        bg1.add(dcard);
        dcard.setText("Debit card");
        dcard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dcardActionPerformed(evt);
            }
        });

        bg1.add(ccard);
        ccard.setText("Credit card");
        ccard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ccardActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dcard)
                    .addComponent(ccard))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dcard)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ccard)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        payment.getContentPane().add(jPanel16);
        jPanel16.setBounds(20, 80, 190, 90);

        jLabel219.setText("Enter the name of the bank");
        payment.getContentPane().add(jLabel219);
        jLabel219.setBounds(30, 200, 150, 14);
        payment.getContentPane().add(bank);
        bank.setBounds(180, 200, 190, 30);

        jLabel220.setText("Enter the card number");
        payment.getContentPane().add(jLabel220);
        jLabel220.setBounds(30, 260, 150, 14);
        payment.getContentPane().add(cno);
        cno.setBounds(180, 250, 190, 30);

        cont.setText(">>CONTINUE");
        cont.setMaximumSize(new java.awt.Dimension(1000, 1000));
        cont.setMinimumSize(new java.awt.Dimension(664, 382));
        cont.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contActionPerformed(evt);
            }
        });
        payment.getContentPane().add(cont);
        cont.setBounds(240, 320, 120, 30);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(758, 491));
        getContentPane().setLayout(null);

        contus.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        contus.setForeground(new java.awt.Color(255, 255, 255));
        contus.setText("CONTACT US  |");
        contus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        contus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                contusMouseClicked(evt);
            }
        });
        getContentPane().add(contus);
        contus.setBounds(410, 10, 100, 17);

        searchfield.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        searchfield.setForeground(new java.awt.Color(255, 255, 255));
        searchfield.setText("SEARCH  |");
        searchfield.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        searchfield.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchfieldMouseClicked(evt);
            }
        });
        getContentPane().add(searchfield);
        searchfield.setBounds(520, 10, 70, 17);

        sup.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        sup.setForeground(new java.awt.Color(255, 255, 255));
        sup.setText("SIGN UP");
        sup.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                supMouseClicked(evt);
            }
        });
        getContentPane().add(sup);
        sup.setBounds(670, 10, 60, 17);

        sin.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        sin.setForeground(new java.awt.Color(255, 255, 255));
        sin.setText("SIGN IN |");
        sin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sinMouseClicked(evt);
            }
        });
        getContentPane().add(sin);
        sin.setBounds(600, 10, 60, 17);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel2.setText("INDIAN AIRLINES");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 370, 440, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/1.png"))); // NOI18N
        jLabel1.setMinimumSize(new java.awt.Dimension(742, 556));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 740, 470);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void contusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contusMouseClicked
        contactus.setVisible(true);
        this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_contusMouseClicked

    private void searchfieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchfieldMouseClicked
gans=1;
        search.setVisible(true);
        this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_searchfieldMouseClicked

    private void supMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supMouseClicked
        signup.setVisible(true);
        this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_supMouseClicked

    private void sinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sinMouseClicked
login.setVisible(true);
this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_sinMouseClicked

    private void lognActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lognActionPerformed
        username=usern.getText();
        password=new String(pword.getPassword());
        usern.setText("");
        pword.setText("");
        String pa="";
        try{
            Class.forName("com.mysql.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/airline","root","rootcat");
            st=conn.createStatement();
            String str="select password,name from user where username='"+username+"';";
            rs=st.executeQuery(str);
            if(rs.next())
            {
                pa=rs.getString("password");
                uname=rs.getString("name");
                name.setText(uname);
            }
            else
            {
                JOptionPane.showMessageDialog(null,"Username does not exist");
             user.setVisible(false);
            }
            st.close();
            conn.close();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
        if(password.equals(pa))
        {
            user.setVisible(true);
            login.setVisible(false);
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Re enter password");
            pword.setText("");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_lognActionPerformed

    private void loginbackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginbackMouseClicked
 usern.setText("");
        pword.setText("");
        this.setVisible(true);
        login.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_loginbackMouseClicked

    private void naActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_naActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_naActionPerformed

    private void monActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_monActionPerformed

    private void createaccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createaccActionPerformed
        String a="no";
        uname=na.getText();
        city=cit.getText();
        state=stat.getText();
        country=coun.getText();
        date=Integer.parseInt(dat.getText());
        month=Integer.parseInt(mon.getText());
        year=Integer.parseInt(yer.getText());
        username=userna.getText();
        password=new String(pass.getPassword());
        codeans=code.getText();
        u=username;
        if(codeans.equals("WgThU"))
        {
            try{
                Class.forName("com.mysql.jdbc.Driver");
                conn=DriverManager.getConnection("jdbc:mysql://localhost/airline","root","rootcat");
                st=conn.createStatement();
                String str1="select username from user where username='"+uname+"';";
                rs=st.executeQuery(str1);
                if(rs.next())
                {
                   a="yes";
                }
                if(a.equals("no"))
                {
                String str="insert into user values('"+uname+"','"+city+"','"+state+"','"+country+"','"+year+"/"+month+"/"+date+"','"+username+"','"+password+"');";
                st.executeUpdate(str);
                JOptionPane.showMessageDialog(null,"Account created successfully");
                        st.close();
                conn.close();
                   name.setText(uname);
                user.setVisible(true);
                signup.setVisible(false);
                }
                else
                {
                    JOptionPane.showMessageDialog(null,"Dupliacte username.Please enter a new user name");
                st.close();
                conn.close();
                }
             
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,e.getMessage());
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Re enter the code");
            code.setText("");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_createaccActionPerformed

    private void codeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codeActionPerformed

    private void newuserbackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newuserbackMouseClicked
        this.setVisible(true);
        signup.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_newuserbackMouseClicked

    private void newuserback1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newuserback1MouseClicked
        this.setVisible(true);
        contactus.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_newuserback1MouseClicked

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        this.setVisible(true);
        user.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_logoutMouseClicked

    private void sflightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sflightActionPerformed
uans=0;
        search.setVisible(true);
user.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_sflightActionPerformed

    private void eprofileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eprofileActionPerformed
        try{
            Class.forName("com.mysql.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/airline","root","rootcat");
            st=conn.createStatement();
            String str="select * from user where username='"+username+"';";
            rs=st.executeQuery(str);
            if(rs.next())
            {
                uname=rs.getString("name");
                city=rs.getString("city");
                state=rs.getString("state");
                country=rs.getString("country");
                date=Integer.parseInt(rs.getString("date_of_birth").substring(8,10));
                month=Integer.parseInt(rs.getString("date_of_birth").substring(5,7));
                year=Integer.parseInt(rs.getString("date_of_birth").substring(0,4));
                password=rs.getString("password");
                ename.setText(uname);
                ecity.setText(city);
                estat.setText(state);
                ecoun.setText(country);
                edat.setText(""+date);
                emon.setText(""+month);
                eyr.setText(""+year);
                epass.setText(password);
      
            }
            rs.close();
            st.close();
            conn.close();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
        update.setVisible(true);
        user.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_eprofileActionPerformed

    private void branchesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_branchesActionPerformed
uans=1;
        book.setVisible(true);
       user.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_branchesActionPerformed

    private void enameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enameActionPerformed

    private void ecityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ecityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ecityActionPerformed

    private void estatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_estatActionPerformed

    private void edatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edatActionPerformed

    private void emonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emonActionPerformed

    private void eyrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eyrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eyrActionPerformed

    private void update1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update1ActionPerformed
        city=ecity.getText();
        state=estat.getText();
        country=ecoun.getText();
        date=Integer.parseInt(edat.getText());
        month=Integer.parseInt(emon.getText());
        year=Integer.parseInt(eyr.getText());
        password=epass.getText();
        try{
            Class.forName("com.mysql.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/pizzahut","root","rootcat");
            st=conn.createStatement();
            String str="update user set city='"+city+"',state='"+state+"',country='"+country+"',dateofbirth='"+year+"/"+month+"/"+date+"',password='"+password+"'where username='"+username+"';";
            st.executeUpdate(str);
            JOptionPane.showMessageDialog(null,"Update successfull");
             user.setVisible(true);
        update.setVisible(false);
            st.close();
            conn.close();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
       
        // TODO add your handling code here:
    }//GEN-LAST:event_update1ActionPerformed

    private void editbackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editbackMouseClicked
        user.setVisible(true);
        update.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_editbackMouseClicked

    private void searActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searActionPerformed
DefaultTableModel nr=(DefaultTableModel)tb1.getModel();
int rows = tb1.getRowCount();
        if (rows > 0) {
            for (int i = 0; i < rows; i++) {
                nr.removeRow(0);
            }
        }
       double p;
        from1=(String)fc1.getSelectedItem();
        to1=(String)tc1.getSelectedItem();
       
         d1=(String)dd.getSelectedItem();
        y1=(String)yd.getSelectedItem();
        m1=(String)md.getSelectedItem();
        d=Integer.parseInt(d1);
        y=Integer.parseInt(y1);
        m=Integer.parseInt(m1);
        int a=0;
   if((from1.equals("MUMBAI")&&to1.equals("DELHI"))||(from1.equals("DELHI")&&to1.equals("MUMBAI"))||(from1.equals("MUMBAI")&&to1.equals("CHENNAI"))||(from1.equals("CHENNAI")&&to1.equals("MUMBAI"))||(from1.equals("MUMBAI")&&to1.equals("KOLKATA"))||(from1.equals("KOLKATA")&&to1.equals("MUMBAI"))||(from1.equals("DELHI")&&to1.equals("KOLKATA"))||(from1.equals("KOLKATA")&&to1.equals("DELHI"))||(from1.equals("KOLKATA")&&to1.equals("CHENNAI"))||(from1.equals("CHENNAI")&&to1.equals("KOLKATA"))||(from1.equals("CHENNAI")&&to1.equals("DELHI"))||(from1.equals("DELHI")&&to1.equals("CHENNAI")))
    a=1;
           else
        JOptionPane.showMessageDialog(null,"Please enter valid values");
   if(a==1)
   {
        try{
            Class.forName("com.mysql.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/airline","root","rootcat");
            st=conn.createStatement();
            String str="select * from flight where fr='"+from1+"' and t='"+to1+"' and date='"+y+"-"+m+"-"+d+"';";
            System.out.println(str);
           rs=st.executeQuery(str);
            while(rs.next())
            {
                p=Double.parseDouble(rs.getString("price"));
              nr.addRow(new Object[]{rs.getString("fr"),rs.getString("t"),rs.getString("date"),rs.getString("departure_time"),rs.getString("arrival_time"),p,p*0.25+p,p+0.50*p});  
            }
            record.setVisible(true);
            search.setVisible(false);
           
            st.close();
            conn.close();
            
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
   }
        // TODO add your handling code here:
    }//GEN-LAST:event_searActionPerformed

    private void showallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showallActionPerformed
DefaultTableModel nr=(DefaultTableModel)tb1.getModel();
int rows = tb1.getRowCount();
        if (rows > 0) {
            for (int i = 0; i < rows; i++) {
                nr.removeRow(0);
            }
        }
      
from1=(String)fc1.getSelectedItem();
        to1=(String)tc1.getSelectedItem();
   
        d1=(String)dd.getSelectedItem();
        m1=(String)md.getSelectedItem();
        y1=(String)yd.getSelectedItem();
        d=Integer.parseInt(d1);
        y=Integer.parseInt(y1);
        m=Integer.parseInt(m1);
        int a=0;
        double p;
   if((from1.equals("MUMBAI")&&to1.equals("DELHI"))||(from1.equals("DELHI")&&to1.equals("MUMBAI"))||(from1.equals("MUMBAI")&&to1.equals("CHENNAI"))||(from1.equals("CHENNAI")&&to1.equals("MUMBAI"))||(from1.equals("MUMBAI")&&to1.equals("KOLKATA"))||(from1.equals("KOLKATA")&&to1.equals("MUMBAI"))||(from1.equals("DELHI")&&to1.equals("KOLKATA"))||(from1.equals("KOLKATA")&&to1.equals("DELHI"))||(from1.equals("KOLKATA")&&to1.equals("CHENNAI"))||(from1.equals("CHENNAI")&&to1.equals("KOLKATA"))||(from1.equals("CHENNAI")&&to1.equals("DELHI"))||(from1.equals("DELHI")&&to1.equals("CHENNAI")))
    a=1;
           else
        JOptionPane.showMessageDialog(null,"Please enter valid values");
   if(a==1)
   {
        try{
            Class.forName("com.mysql.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/airline","root","rootcat");
            st=conn.createStatement();
            String str="select * from flight where fr='"+from1+"' and t='"+to1+"';";
            rs=st.executeQuery(str);
            while(rs.next())
            {
                  p=Double.parseDouble(rs.getString("price"));
            nr.addRow(new Object[]{rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),p,0.25*p+p,p*0.50+p});     
            }
             record.setVisible(true);
            search.setVisible(false);
            st.close();
            conn.close();
           
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e.getMessage());
        } 
   }
        // TODO add your handling code here:
    }//GEN-LAST:event_showallActionPerformed

    private void editback1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editback1MouseClicked
if(gans==1)        
{gans=0;
    this.setVisible(true);
        search.setVisible(false);
}
else
{
    user.setVisible(true);
    search.setVisible(false);
}
        // TODO add your handling code here:
    }//GEN-LAST:event_editback1MouseClicked

    private void okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okActionPerformed
        Display.setText("");
        totprice=0;
     
        end.setVisible(true);
        Bill.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_okActionPerformed

    private void loutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loutActionPerformed
        this.setVisible(true);
        end.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_loutActionPerformed

    private void gouseraccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gouseraccActionPerformed
        user.setVisible(true);
        end.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_gouseraccActionPerformed

    private void dcardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dcardActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_dcardActionPerformed

    private void ccardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ccardActionPerformed
 
        // TODO add your handling code here:
    }//GEN-LAST:event_ccardActionPerformed

    private void contActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contActionPerformed
     if(clas.equals("ECONOMY"))
    eseats=eseats-seats;
else if(clas.equals("BUSINESS"))
    bseats=bseats-seats;
else
    fseats=fseats-seats;
            String bname,creditno,paymode="";
            bname=bank.getText();
            creditno=cno.getText();
            if(dcard.isSelected()==true)
                paymode="Debit card";
            else if(ccard.isSelected()==true)
                paymode="Credit card";
            else
                 JOptionPane.showMessageDialog(null,"Please select the payment mode");
            if(bname.equals("")|| creditno.equals(""))
            JOptionPane.showMessageDialog(null,"Please enter the credit card details");
            else
            {
               try{
                Class.forName("com.mysql.jdbc.Driver");
                conn=DriverManager.getConnection("jdbc:mysql://localhost/airline","root","rootcat");
                st=conn.createStatement();
                String str1="select max(bill_no) from bill;";
                rs=st.executeQuery(str1);
                if(rs.next())
                {
                    String n=rs.getString(1);
                    if(n==null)
                        no=0;
                    else
                no=Integer.parseInt(n);
                }
                String str="insert into bill values("+(++no)+",'"+username+"','"+uname+"','"+paymode+"','"+bname+"','"+creditno+"',"+seats+","+totprice+",'"+book_from+"','"+book_to+"','"+book_class+"','yes');";
                st.executeUpdate(str);
                str="select * from bill where bill_no='"+no+"';";
            rs=st.executeQuery(str);
            if(rs.next())
            {
                Display.append("Bill no:"+rs.getString("bill_no")+"\nName:"+rs.getString("name")+"\nPayment mode:"+rs.getString("paymode")+"\nName of bank:"+rs.getString("bname")+"\nCard number:"+rs.getString("cnumber")+"\nTotal seats booked:"+rs.getString("seats")+"\nTotal amount:"+rs.getString("amt"));
      
            }
            bank.setText("");
            cno.setText("");
                Bill.setVisible(true);
                Display.append("\n" + "Thank You");
                payment.dispose();
                        st.close();
                conn.close();
                
             
            }
            catch(Exception e)
            {
               
                JOptionPane.showMessageDialog(null,e.getMessage());
            }
        } 
            
         
    
        // TODO add your handling code here:
    }//GEN-LAST:event_contActionPerformed

    private void proceedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proceedActionPerformed
DefaultTableModel nr=(DefaultTableModel)tb1.getModel();
uans=1;
seats=Integer.parseInt(seat.getText());
from1=(String)fc.getSelectedItem();
clas=(String)cc.getSelectedItem();
to1=(String)tc.getSelectedItem();
book_from=from1;
book_to=to1;
book_class=clas;
int rows = tb1.getRowCount();
        if (rows > 0) {
            for (int i = 0; i < rows; i++) {
                nr.removeRow(0);
            }
        }
       double p;
       int a=0;
        d1=(String)dc1.getSelectedItem();
        m1=(String)dc2.getSelectedItem();
        y1=(String)dc3.getSelectedItem();
        d=Integer.parseInt(d1);
        y=Integer.parseInt(y1);
        m=Integer.parseInt(m1);
 if((from1.equals("MUMBAI")&&to1.equals("DELHI"))||(from1.equals("DELHI")&&to1.equals("MUMBAI"))||(from1.equals("MUMBAI")&&to1.equals("CHENNAI"))||(from1.equals("CHENNAI")&&to1.equals("MUMBAI"))||(from1.equals("MUMBAI")&&to1.equals("KOLKATA"))||(from1.equals("KOLKATA")&&to1.equals("MUMBAI"))||(from1.equals("DELHI")&&to1.equals("KOLKATA"))||(from1.equals("KOLKATA")&&to1.equals("DELHI"))||(from1.equals("KOLKATA")&&to1.equals("CHENNAI"))||(from1.equals("CHENNAI")&&to1.equals("KOLKATA"))||(from1.equals("CHENNAI")&&to1.equals("DELHI"))||(from1.equals("DELHI")&&to1.equals("CHENNAI")))
    a=1;
           else
        JOptionPane.showMessageDialog(null,"Please enter valid values");
   if(a==1)
   {

        try{
            Class.forName("com.mysql.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/airline","root","rootcat");
            st=conn.createStatement();
             String str="select count(*) as count from bill where source='"+from1+"' and dest='"+to1+"' and b_class='"+clas+"';";
            rs=st.executeQuery(str);
            int count=0;
            while(rs.next())
            {
                count=rs.getInt("count");
            }
             str="select * from flight where fr='"+from1+"' and t='"+to1+"' and date='"+y+"-"+m+"-"+d+"';";
            rs=st.executeQuery(str);
            while(rs.next())
            {
                p=Double.parseDouble(rs.getString("price"));
              if(clas.equals("ECONOMY"))
              nr.addRow(new Object[]{rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),p});  
             else if(clas.equals("BUSINESS"))
                  nr.addRow(new Object[]{rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),"",p+0.25*p});
              else 
                  nr.addRow(new Object[]{rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),"","",p+0.50*p});
                 
            }
            seat.setText("");
            if(count>5)
            {
                try{
                Class.forName("com.mysql.jdbc.Driver");
                conn=DriverManager.getConnection("jdbc:mysql://localhost/airline","root","rootcat");
                st=conn.createStatement();
                String str1="select max(bill_no) from bill;";
                rs=st.executeQuery(str1);
                if(rs.next())
                {
                    String n=rs.getString(1);
                    if(n==null)
                        no=0;
                    else
                no=Integer.parseInt(n);
                }
                str="insert into bill values("+(++no)+",'"+username+"','"+uname+"','','','',"+seats+","+totprice+",'"+book_from+"','"+book_to+"','"+book_class+"','no';";
                st.executeUpdate(str);
                JOptionPane.showMessageDialog(null,"Sorry tickets are not available");
                        st.close();
                conn.close();
                
             
            }
            catch(Exception e)
            {
               
                JOptionPane.showMessageDialog(null,e.getMessage());
            }
            }
            else
            {
                 try{
            Class.forName("com.mysql.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/airline","root","rootcat");
            st=conn.createStatement();
           int k =3;
			int co=0;
			rs = st.executeQuery("select count(*) as count from flight");
            	while (rs.next()) {
            		 co=rs.getInt("count");
            	}
			int n=co; 

                   int cluster_center[] = new int[k];
			int i=0, iter=1;
			ArrayList<Integer> dataItems = new ArrayList<Integer>();
			ArrayList<Integer> cz = new ArrayList<Integer>();
			ArrayList<Integer> oldCz = new ArrayList<Integer>();
			ArrayList<Integer> row = new ArrayList<Integer>();
			ArrayList<ArrayList<Integer>> groups = new ArrayList<ArrayList<Integer>>();
			for(i=0; i<k; i++) {
				groups.add(new ArrayList<Integer>()); //error new ArrayList<>();
			}
                        rs = st.executeQuery("select distance from flight where fr='"+from1+"' and t='"+to1+"'");
            	int dist=0;
                        if (rs.next()) {
            		 dist=rs.getInt("distance");
                }
			rs= st.executeQuery("SELECT distinct distance FROM flight");
			i=0;
			
			while(rs.next()) {
				int temp=(int)rs.getDouble("distance");
				
				dataItems.add(temp);
				if (i<k) {
					cz.add(dataItems.get(i));
				}
				i++;
			}
			
			
			
			do{
				for (int aItem : dataItems) {
					for (int c : cz) {
						row.add(Math.abs(c - aItem));
					}
					groups.get(row.indexOf(Collections.min(row))).add(aItem);
					row.removeAll(row);
				}
				for(i=0; i<k; i++) {
					if(iter == 1) {
						oldCz.add(cz.get(i));
					} else {
						oldCz.set(i, cz.get(i));
					}
					if(!groups.get(i).isEmpty()) {
                                            int sum = 0;
		for(Integer value : groups.get(i)) {
			sum = sum + value;
		}
		int avg= sum / groups.get(i).size();
						cz.set(i,avg);
					}
				}
				if(!cz.equals(oldCz)) {
					for (i=0; i<groups.size(); i++) {
						groups.get(i).removeAll(groups.get(i));
					}
				}
				iter++;
			} while(!cz.equals(oldCz));
			
			for(i=0; i<cz.size(); i++) {
				//System.out.println("New C" + (i + 1) + " " + cz.get(i));
			}
                        String str1="",fr1="",to1="";
                        int index=0,ad=0;
			for(i=0; i<groups.size(); i++) {
                            //str="Group " + (i + 1)+"\n"+groups.get(i).toString()+"\nSource  Dest\n";
                            for(int j=0;j<groups.get(i).size();j++)
                            {
                                if(groups.get(i).get(j)==dist){
                                    ad=1;
                                    index=i;
                                    break;
                                }
                            }
                            if(ad==1)
                                break;
                        }
				
			for(int j=0;j<groups.get(index).size();j++)
                            {
                rs = st.executeQuery("select fr,t from flight where distance="+groups.get(index).get(j));
            	if (rs.next()) {
            		 fr1=rs.getString("fr");
                         to1=rs.getString("t");    
            	}
                str1=str1+fr1+" to "+to1+"    ";
                             
                            }
                             other.setText(str1);

                        
			//System.out.println("Number of Iterations: " + iter);
	
            st.close();
            conn.close();
           
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
           
        
                record.setVisible(true);
            }
            book.setVisible(false);
            st.close();
            conn.close();
           
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
   }
        // TODO add your handling code here:
    }//GEN-LAST:event_proceedActionPerformed

    private void fcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fcActionPerformed

    private void tcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tcActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
if(uans==0&&gans==0)
{
    book.setVisible(true);
    record.setVisible(false);
}
 if(uans==1&&gans==0)
{
    if((from1.equals("MUMBAI")&&to1.equals("DELHI"))||(from1.equals("DELHI")&&to1.equals("MUMBAI")))
            price=3500;
    else if((from1.equals("MUMBAI")&&to1.equals("CHENNAI"))||(from1.equals("CHENNAI")&&to1.equals("MUMBAI")))
            price=3300;
    else if((from1.equals("MUMBAI")&&to1.equals("KOLKATA"))||(from1.equals("KOLKATA")&&to1.equals("MUMBAI")))
            price=4000;
    else if((from1.equals("DELHI")&&to1.equals("KOLKATA"))||(from1.equals("KOLKATA")&&to1.equals("DELHI")))
            price=4200;
    else if((from1.equals("KOLKATA")&&to1.equals("CHENNAI"))||(from1.equals("CHENNAI")&&to1.equals("KOLKATA")))
            price=3700;
    else if((from1.equals("CHENNAI")&&to1.equals("DELHI"))||(from1.equals("DELHI")&&to1.equals("CHENNAI")))
            price=5000;
    else
        JOptionPane.showMessageDialog(null,"Please enter valid values");
    if(clas.equals("ECONOMY"))
    totprice=price*seats;
else if(clas.equals("BUSINESS"))
   totprice=(price*0.25+price)*seats;
else
    totprice=(price*0.50+price)*seats;
 totamt.setText("Your total amount is "+totprice);
 payment.setVisible(true);
 record.setVisible(false);
}
 else if(gans==1)
{gans=0;
    login.setVisible(true);
    record.setVisible(false);
}
else
    ;
    
    
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void fc1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fc1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fc1ActionPerformed

    private void tc1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tc1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tc1ActionPerformed

    private void jLabel21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseClicked
user.setVisible(true);
book.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel21MouseClicked

    private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseClicked
 search.setVisible(true);
    record.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel18MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
uans=1;
from1=(String)fc.getSelectedItem();
to1=(String)tc.getSelectedItem();
       double p;
       int a=0;
 if((from1.equals("MUMBAI")&&to1.equals("DELHI"))||(from1.equals("DELHI")&&to1.equals("MUMBAI"))||(from1.equals("MUMBAI")&&to1.equals("CHENNAI"))||(from1.equals("CHENNAI")&&to1.equals("MUMBAI"))||(from1.equals("MUMBAI")&&to1.equals("KOLKATA"))||(from1.equals("KOLKATA")&&to1.equals("MUMBAI"))||(from1.equals("DELHI")&&to1.equals("KOLKATA"))||(from1.equals("KOLKATA")&&to1.equals("DELHI"))||(from1.equals("KOLKATA")&&to1.equals("CHENNAI"))||(from1.equals("CHENNAI")&&to1.equals("KOLKATA"))||(from1.equals("CHENNAI")&&to1.equals("DELHI"))||(from1.equals("DELHI")&&to1.equals("CHENNAI")))
    a=1;
           else
        JOptionPane.showMessageDialog(null,"Please enter valid values");
   if(a==1)
   {
       int n=0;
        try{
            Class.forName("com.mysql.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/airline","root","rootcat");
            st=conn.createStatement();
            rs = st.executeQuery("select count(*) as count from flight");
            while (rs.next()) {
            	 	n=rs.getInt("count");
            }
            double val_x[]=new double[n];
            double val_y[]=new double[n];
            double pr=0;
            String str="select avg(price) as avg from flight where fr='"+from1+"' and t='"+to1+"';";
            rs=st.executeQuery(str);
            while (rs.next()) {
            	 	pr=rs.getDouble("avg");
            }
            str="select * from flight where fr='"+from1+"' and t='"+to1+"';";
            rs=st.executeQuery(str);
            int i=0;
            double sum_x=0,sum_y=0;
            while(rs.next())
            {
                val_x[i]=Double.parseDouble(rs.getString("price"));
                val_y[i]=Double.parseDouble(rs.getString("discounted_price"));
                sum_x=sum_x+val_x[i];
            	sum_y=sum_y+val_y[i];
                i++;
            }
            double mean_x=(double)sum_x/n;
            double mean_y=(double)sum_y/n;
            double num=0,den=0;
            for(i=0;i<n;i++){
            		num=num+(val_x[i]-mean_x)*(val_y[i]-mean_y);
            		den=den+Math.pow((val_x[i]-mean_x),2);
            	}
            double w1=num/den;
            double w0=mean_y-w1*mean_x;
            double dis_pr=w0+w1*pr;
            JOptionPane.showMessageDialog(null,"The actual price is: Rs."+pr+"\nThe predicted discounted price is: Rs."+Math.floor(dis_pr*100)/100);

            st.close();
            conn.close();
           
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
   }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
uans=1;
from1=(String)fc.getSelectedItem();
to1=(String)tc.getSelectedItem();
String c1=(String)cc.getSelectedItem();
       double p;
       int a=0;
 if((from1.equals("MUMBAI")&&to1.equals("DELHI"))||(from1.equals("DELHI")&&to1.equals("MUMBAI"))||(from1.equals("MUMBAI")&&to1.equals("CHENNAI"))||(from1.equals("CHENNAI")&&to1.equals("MUMBAI"))||(from1.equals("MUMBAI")&&to1.equals("KOLKATA"))||(from1.equals("KOLKATA")&&to1.equals("MUMBAI"))||(from1.equals("DELHI")&&to1.equals("KOLKATA"))||(from1.equals("KOLKATA")&&to1.equals("DELHI"))||(from1.equals("KOLKATA")&&to1.equals("CHENNAI"))||(from1.equals("CHENNAI")&&to1.equals("KOLKATA"))||(from1.equals("CHENNAI")&&to1.equals("DELHI"))||(from1.equals("DELHI")&&to1.equals("CHENNAI")))
    a=1;
           else
        JOptionPane.showMessageDialog(null,"Please enter valid values");
   if(a==1)
   {
        try{
            Class.forName("com.mysql.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/airline","root","rootcat");
            st=conn.createStatement();
            int n=0,m=0,temp1=0,temp2;
            rs = st.executeQuery("select count(*) as count from bill where availability='yes'");
            while (rs.next()) {
            	 	n=rs.getInt("count");
            }
            rs = st.executeQuery("select count(*) as count from bill where availability='no'");
            while (rs.next()) {
            	 	m=rs.getInt("count");
            }
            int tot=m+n;
           double prob_yes=(double)n/tot;
           double prob_no=(double)m/tot;

              rs= st.executeQuery("select count(*) as count from bill where availability='yes' and source='"+from1+"'");
            while (rs.next()) {
            	 temp1=rs.getInt("count");
            }
            double src_yes=(double)temp1/n;
             rs= st.executeQuery("select count(*) as count from bill where availability='no' and source='"+from1+"'");
            while (rs.next()) {
            	 temp1=rs.getInt("count");
            }
            double src_no=(double)temp1/m;
            
            rs= st.executeQuery("select count(*) as count from bill where availability='yes' and dest='"+to1+"'");
            while (rs.next()) {
            	 temp1=rs.getInt("count");
            }
            double dest_yes=(double)temp1/n;
             rs= st.executeQuery("select count(*) as count from bill where availability='no' and dest='"+to1+"'");
            while (rs.next()) {
            	 temp1=rs.getInt("count");
            }
            double dest_no=(double)temp1/m;

                        
             rs= st.executeQuery("select count(*) as count from bill where availability='yes' and b_class='"+c1+"'");
            while (rs.next()) {
            	 temp1=rs.getInt("count");
            }
            double c_yes=(double)temp1/n;
             rs= st.executeQuery("select count(*) as count from bill where availability='no' and b_class='"+c1+"'");
            while (rs.next()) {
            	 temp1=rs.getInt("count");
            }
            double c_no=(double)temp1/m;

            double yes=prob_yes*src_yes*dest_yes*c_yes;
		    double no=prob_no*src_no*dest_no*c_no;
                    
            if(yes>no)
            JOptionPane.showMessageDialog(null,"The ticket might be available");
            else
                JOptionPane.showMessageDialog(null,"The ticket might not be available"); 

            st.close();
            conn.close();
           
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
   }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        try{
            Class.forName("com.mysql.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/airline","root","rootcat");
            st=conn.createStatement();
           int k =3;
			int count=0;
			rs = st.executeQuery("select count(*) as count from flight");
            	while (rs.next()) {
            		 count=rs.getInt("count");
            	}
			int n=count; 

                   int cluster_center[] = new int[k];
			int i=0, iter=1;
			ArrayList<Integer> dataItems = new ArrayList<Integer>();
			ArrayList<Integer> cz = new ArrayList<Integer>();
			ArrayList<Integer> oldCz = new ArrayList<Integer>();
			ArrayList<Integer> row = new ArrayList<Integer>();
			ArrayList<ArrayList<Integer>> groups = new ArrayList<ArrayList<Integer>>();
			for(i=0; i<k; i++) {
				groups.add(new ArrayList<Integer>()); //error new ArrayList<>();
			}
			rs= st.executeQuery("SELECT distinct distance FROM flight");
			i=0;
			
			while(rs.next()) {
				int temp=(int)rs.getDouble("distance");
				
				dataItems.add(temp);
				if (i<k) {
					cz.add(dataItems.get(i));
				}
				i++;
			}
			
			
			
			do{
				for (int aItem : dataItems) {
					for (int c : cz) {
						row.add(Math.abs(c - aItem));
					}
					groups.get(row.indexOf(Collections.min(row))).add(aItem);
					row.removeAll(row);
				}
				for(i=0; i<k; i++) {
					if(iter == 1) {
						oldCz.add(cz.get(i));
					} else {
						oldCz.set(i, cz.get(i));
					}
					if(!groups.get(i).isEmpty()) {
                                            int sum = 0;
		for(Integer value : groups.get(i)) {
			sum = sum + value;
		}
		int avg= sum / groups.get(i).size();
						cz.set(i,avg);
					}
				}
				if(!cz.equals(oldCz)) {
					for (i=0; i<groups.size(); i++) {
						groups.get(i).removeAll(groups.get(i));
					}
				}
				iter++;
			} while(!cz.equals(oldCz));
			
			for(i=0; i<cz.size(); i++) {
				System.out.println("New C" + (i + 1) + " " + cz.get(i));
			}
                        String str,fr="",to="";
			for(i=0; i<groups.size(); i++) {
                            str="Group " + (i + 1)+"\n"+groups.get(i).toString()+"\nSource  Dest\n";
 
				
			for(int j=0;j<groups.get(i).size();j++)
                            {
                                rs = st.executeQuery("select fr,t from flight where distance="+groups.get(i).get(j));
            	if (rs.next()) {
            		 fr=rs.getString("fr");
                         to=rs.getString("t");    
            	}
                str=str+fr+"  "+to+"\n";
                             
                            }
                                        JOptionPane.showMessageDialog(null,str);

                        }
			//System.out.println("Number of Iterations: " + iter);
	
		
	

            st.close();
            conn.close();
           
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e.getMessage());
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame Bill;
    private javax.swing.JTextArea Display;
    private javax.swing.JTextField bank;
    private javax.swing.ButtonGroup bg1;
    private javax.swing.JFrame book;
    private javax.swing.JButton branches;
    private javax.swing.JComboBox cc;
    private javax.swing.JRadioButton ccard;
    private javax.swing.JTextField cit;
    private javax.swing.JTextField cno;
    private javax.swing.JTextField code;
    private javax.swing.JButton cont;
    private javax.swing.JFrame contactus;
    private javax.swing.JLabel contus;
    private javax.swing.JTextField coun;
    private javax.swing.JButton createacc;
    private javax.swing.JTextField dat;
    private javax.swing.JComboBox dc1;
    private javax.swing.JComboBox dc2;
    private javax.swing.JComboBox dc3;
    private javax.swing.JRadioButton dcard;
    private javax.swing.JComboBox dd;
    private javax.swing.JTextField ecity;
    private javax.swing.JTextField ecoun;
    private javax.swing.JTextField edat;
    private javax.swing.JLabel editback;
    private javax.swing.JLabel editback1;
    private javax.swing.JTextField emon;
    private javax.swing.JTextField ename;
    private javax.swing.JFrame end;
    private javax.swing.JTextField epass;
    private javax.swing.JButton eprofile;
    private javax.swing.JTextField estat;
    private javax.swing.JTextField eyr;
    private javax.swing.JComboBox fc;
    private javax.swing.JComboBox fc1;
    private javax.swing.JButton gouseracc;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel100;
    private javax.swing.JLabel jLabel101;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel217;
    private javax.swing.JLabel jLabel219;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel220;
    private javax.swing.JLabel jLabel221;
    private javax.swing.JLabel jLabel222;
    private javax.swing.JLabel jLabel223;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel90;
    private javax.swing.JLabel jLabel91;
    private javax.swing.JLabel jLabel92;
    private javax.swing.JLabel jLabel93;
    private javax.swing.JLabel jLabel94;
    private javax.swing.JLabel jLabel95;
    private javax.swing.JLabel jLabel96;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JFrame login;
    private javax.swing.JLabel loginback;
    private javax.swing.JButton logn;
    private javax.swing.JLabel logout;
    private javax.swing.JButton lout;
    private javax.swing.JComboBox md;
    private javax.swing.JTextField mon;
    private javax.swing.JTextField na;
    private javax.swing.JLabel name;
    private javax.swing.JLabel newuserback;
    private javax.swing.JLabel newuserback1;
    private javax.swing.JButton ok;
    private javax.swing.JLabel other;
    private javax.swing.JPasswordField pass;
    private javax.swing.JDialog payment;
    private javax.swing.JButton proceed;
    private javax.swing.JPasswordField pword;
    private javax.swing.JFrame record;
    private javax.swing.JButton sear;
    private javax.swing.JFrame search;
    private javax.swing.JLabel searchfield;
    private javax.swing.JTextField seat;
    private javax.swing.JButton sflight;
    private javax.swing.JButton showall;
    private javax.swing.JFrame signup;
    private javax.swing.JLabel sin;
    private javax.swing.JTextField stat;
    private javax.swing.JLabel sup;
    private javax.swing.JTable tb1;
    private javax.swing.JComboBox tc;
    private javax.swing.JComboBox tc1;
    private javax.swing.JLabel totamt;
    private javax.swing.JFrame update;
    private javax.swing.JButton update1;
    private javax.swing.JFrame user;
    private javax.swing.JTextField usern;
    private javax.swing.JTextField userna;
    private javax.swing.JComboBox yd;
    private javax.swing.JTextField yer;
    // End of variables declaration//GEN-END:variables
}
